### ISSUE TITLE
Health Check fails on jbergstroem/mariadb-alpine:latest

### ISSUE THREAD

**Issue by caveman99** [jbergstroem/mariadb-alpine#122] opened 2022-03-13 11:23 UTC
The health check (in this case in portainer) is showing 'unhealthy' after updating from 10.4.x to 10.6.x series. 

The DB itself works fine.

**Comment by caveman99** [comment] 2022-03-13 12:35
Additional observation: a fresh container is 'healthy' - trying a full mysql_upgrade now.

**Comment by jbergstroem** [comment] 2022-03-13 13:21
Thanks for the report, I will investigate

**Comment by jbergstroem** [comment] 2022-10-09 15:30
Closing seeing how I cant reproduce anyy longer. Feel free to reopen if you are still experiencing it.

**Closed by jbergstroem** 2022-10-09 15:30 UTC
